org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.20.1
minecraft_version_range=1.20.1
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1


mod_id=areaffectclouds3d
mod_name=3D Area Effect Clouds
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=insane96mcp.areaeffectclouds3d
mod_authors=Insane96MCP
mod_description=Replace the boring circles Area Effect Clouds with Spheres

lib_version=1.20.0
lib_version_range=[1.20.0,)